In [4]:
import numpy as np

#from: https://github.com/gazay/dlnd_tv_script_generation/blob/master/dlnd_tv_script_generation.ipynb
def get_batches1(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    # TODO: Implement Function
    n_batches = len(int_text) // (batch_size * seq_length)
    result = []
    for i in range(n_batches):
        inputs = []
        targets = []
        for j in range(batch_size):
            idx = i * seq_length + j * seq_length
            inputs.append(int_text[idx:idx + seq_length])
            targets.append(int_text[idx + 1:idx + seq_length + 1])
        result.append([inputs, targets])
    return np.array(result)

def get_batches(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    # TODO: Implement Function
    #helpful diagramm:
    # https://stackoverflow.com/questions/44381450/doubts-regarding-batch-size-and-time-steps-in-rnn
    char_per_batch = batch_size * seq_length
    num_batches = len(int_text) // char_per_batch
    #int_text_dropped_end = int_text[:char_per_batch * num_batches]
    
    #create chunks. works, but has wrong order of chunks
    inp_chunk=np.reshape(int_text[:char_per_batch * num_batches], [-1, batch_size, seq_length])
    out_chunk=np.reshape(int_text[1:char_per_batch * num_batches
                                 +1], [-1, batch_size,seq_length])
    out = np.stack((inp_chunk, out_chunk),1)
    
    #other try
    #int_text = np.array(int_text)
    ret=[]
    out_inp_delta = 1
    for batch in range(num_batches):
        inp = []
        out = []
        for batch_token in range(batch_size):
            idx_inp_start = seq_length*(batch_token + batch)
            idx_inp_end = idx_inp_start + seq_length
            inp.append(int_text[idx_inp_start:idx_inp_end])
            out.append(int_text[idx_inp_start + out_inp_delta:idx_inp_end+out_inp_delta])
            #print(inp)
            #print("---")
            #print(out)
        ret.append([inp, out])
        #print(ret)
        #print(np.array(ret))
    

    
    return np.array(ret)

b = get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],2, 3)
c = get_batches1([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],2, 3)
print(b)
print("---")
print(c)
print(b.shape)
print (b==c)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 2  3  4]
   [ 5  6  7]]]


 [[[ 4  5  6]
   [ 7  8  9]]

  [[ 5  6  7]
   [ 8  9 10]]]]
---
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 2  3  4]
   [ 5  6  7]]]


 [[[ 4  5  6]
   [ 7  8  9]]

  [[ 5  6  7]
   [ 8  9 10]]]]
(2, 2, 2, 3)
[[[[ True  True  True]
   [ True  True  True]]

  [[ True  True  True]
   [ True  True  True]]]


 [[[ True  True  True]
   [ True  True  True]]

  [[ True  True  True]
   [ True  True  True]]]]
